// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMN.Data;

namespace PMN.Data.Migrations
{
    [DbContext(typeof(PMNContext))]
    [Migration("20200807000540_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PMN.Models.Project", b =>
                {
                    b.Property<int>("NidProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatProjectEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatProjectStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesProject")
                        .HasColumnType("nvarchar(240)")
                        .HasMaxLength(240);

                    b.Property<string>("TidProject")
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("NidProject");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PMN.Models.ProjectTask", b =>
                {
                    b.Property<int>("NidTask")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DesTask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlgTaskDone")
                        .HasColumnType("bit");

                    b.Property<int>("NidProject")
                        .HasColumnType("int");

                    b.Property<string>("TidTask")
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<TimeSpan>("TimExpected")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimSpent")
                        .HasColumnType("time");

                    b.HasKey("NidTask");

                    b.HasIndex("NidProject");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("PMN.Models.ProjectTask", b =>
                {
                    b.HasOne("PMN.Models.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("NidProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
